language: "DE_de"
mysql:
  ip: ""
  port: ""
  database: ""
  username: ""
  password: ""
gamesettings:
  starttime: 30
  gametime: 3600
  maxplayer: 24
  minplayer: 2
  mapsize: 500
  landscan:
    step: 32            # Rasterabstand (je größer, desto schneller/grober)
    sample_radius: 192  # Radius für die Biome-Stichprobe um einen Kandidaten
    search_radius: 2048 # wie weit um 0/0 gesucht wird
    max_ocean_ratio: 0.15
  pregen:
    enabled: true
    spawn_chunk_radius: 4
    batch_chunks: 32
  border:
    active: true
    startshrink: 120
    minsize: 100